- name: Install grafana
  ansible.builtin.dnf:
    name:
      - grafana

- name: Grafana configuration file copy
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini

- name: Reload systemd
  command: systemctl daemon-reload

- name: Grafana server started
  service:
    name: grafana-server
    enabled: true
    state: started

- name: Check if Grafana is accessible.
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200
