- name: Copy pipeline code to cluster
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/src/"
    dest: /home/almalinux/sentiment_analysis/
    owner: almalinux
    group: almalinux
    mode: '0755'

- name: Install pipeline code package
  ansible.builtin.pip:
    name: /home/almalinux/sentiment_analysis/
  become: yes
