- name: Install English localisation
  ansible.builtin.dnf:
    name:
      - glibc-langpack-en
    state: latest
- name: Set en-GB localization
  shell: "localectl set-locale en_GB.UTF-8"
- name: Set time-zone
  shell: "timedatectl set-timezone Europe/London"