---
# tasks file for spark
- include_tasks: download.yaml
- include_tasks: configure.yaml
- include_tasks: start_master.yaml
  when: "'hostnode' in group_names"
- include_tasks: start_workers.yaml
  when: "'workers' in group_names"
